version: '3.1'

# 실행하고 싶은 도커 이미지들
services:
  # 이름
  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: pnpm run start:dev user
    ports:
      - '3001:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # 이건 연동하지 말라라는 뜻
