apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config-map
data:
  HTTP_PORT: "3000"
  TCP_PORT: "3001"
  GRPC_URL: "0.0.0.0:3001"
  ACCESS_TOKEN_SECRET: "your_access_token_secret_key"
  REFRESH_TOKEN_SECRET: "your_refresh_token_secret_key"









